require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/places", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Place. As you add validations to Place, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      name: "Chicago",
      description: "As a multicultural city that thrives on the harmony and diversity of its neighborhoods, Chicago today embodies the values of America's heartland-integrity, hard work and community and reflects the ideals in the social fabric of its 77 distinct neighborhoods.",
      latitude: 41.8781136,
      longitude: -87.6297982
    }
  }

  let(:invalid_attributes) {
    {
      name: "",
      description: "",
      latitude: "latitude",
      longitude: "longitude"
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Place.create! valid_attributes
      get places_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      place = Place.create! valid_attributes
      get place_url(place)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_place_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      place = Place.create! valid_attributes
      get edit_place_url(place)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Place" do
        expect {
          post places_url, params: { place: valid_attributes }
        }.to change(Place, :count).by(1)
      end

      it "redirects to the created place" do
        post places_url, params: { place: valid_attributes }
        expect(response).to redirect_to(place_url(Place.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Place" do
        expect {
          post places_url, params: { place: invalid_attributes }
        }.to change(Place, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post places_url, params: { place: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: "Chicago",
          description: "As a multicultural city that thrives on the harmony and diversity of its neighborhoods, Chicago today embodies the values of America's heartland-integrity, hard work and community and reflects the ideals in the social fabric of its 77 distinct neighborhoods. The greatest city in the world!",
          latitude: 41.8781136,
          longitude: -87.6297982
        }
      }

      it "updates the requested place" do
        place = Place.create! valid_attributes
        patch place_url(place), params: { place: new_attributes }
        place.reload
        expect(place.description).to include("THE GREATEST CITY IN THE WORLD!")
      end

      it "redirects to the place" do
        place = Place.create! valid_attributes
        patch place_url(place), params: { place: new_attributes }
        place.reload
        expect(response).to redirect_to(place_url(place))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        place = Place.create! valid_attributes
        patch place_url(place), params: { place: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested place" do
      place = Place.create! valid_attributes
      expect {
        delete place_url(place)
      }.to change(Place, :count).by(-1)
    end

    it "redirects to the places list" do
      place = Place.create! valid_attributes
      delete place_url(place)
      expect(response).to redirect_to(places_url)
    end
  end
end
